apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-easy
  labels:
    app: ctf-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-easy
  template:
    metadata:
      labels:
        app: ctf-easy
    spec:
      containers:
        - name: ctf-easy
          image: ctf-easy:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ctf-easy
spec:
  selector:
    app: ctf-easy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
