apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-elite
  labels:
    app: ctf-elite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-elite
  template:
    metadata:
      labels:
        app: ctf-elite
    spec:
      containers:
        - name: ctf-elite
          image: ctf-elite:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ctf-elite
spec:
  selector:
    app: ctf-elite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
