apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-mythical
  labels:
    app: ctf-mythical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-mythical
  template:
    metadata:
      labels:
        app: ctf-mythical
    spec:
      containers:
        - name: ctf-mythical
          image: ctf-mythical:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ctf-mythical
spec:
  selector:
    app: ctf-mythical
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
